<div class="admin-form-grid admin-blog-form-grid">
    <label class="admin-field admin-field-full"><span>Tiêu đề</span><input name="title" value="{{ old('title', $post?->title) }}" maxlength="255" required></label>
    <label class="admin-field"><span>Slug <small>Để trống để tự tạo</small></span><input name="slug" value="{{ old('slug', $post?->slug) }}" maxlength="255"></label>
    <label class="admin-field"><span>Danh mục</span><select name="blog_category_id"><option value="">Chưa phân loại</option>@foreach ($categories as $category)<option value="{{ $category->getKey() }}" @selected((string) old('blog_category_id', $post?->blog_category_id) === (string) $category->getKey())>{{ $category->name }}</option>@endforeach</select></label>
    <label class="admin-field admin-field-full"><span>Tóm tắt</span><textarea name="excerpt" rows="3" maxlength="1000">{{ old('excerpt', $post?->excerpt) }}</textarea></label>
    <label class="admin-field admin-field-full"><span>Nội dung bài viết</span><textarea name="content" rows="18" required data-rich-text-editor>{{ old('content', $post?->content) }}</textarea><small>Trình soạn thảo hỗ trợ tiêu đề, ảnh, liên kết, bảng và định dạng nội dung.</small></label>
    <label class="admin-field"><span>Ảnh đại diện</span><input name="featured_image" type="file" accept="image/jpeg,image/png,image/webp">@if ($post?->featured_image_url)<img class="admin-image-preview" src="{{ $post->featured_image_url }}" alt="">@endif</label>
    <label class="admin-field"><span>Alt ảnh đại diện</span><input name="featured_image_alt" value="{{ old('featured_image_alt', $post?->featured_image_alt) }}" maxlength="255"></label>
    @if ($post?->featured_image_path)<label class="admin-check"><input name="remove_featured_image" type="checkbox" value="1"><span>Xóa ảnh đại diện hiện tại</span></label>@endif
    <fieldset class="admin-fieldset admin-field-full"><legend>Thẻ</legend><div class="admin-option-grid">@foreach ($tags as $tag)<label><input name="tag_ids[]" type="checkbox" value="{{ $tag->getKey() }}" @checked(in_array($tag->getKey(), old('tag_ids', $post?->tags->pluck('id')->all() ?? [])))><span>{{ $tag->name }}</span></label>@endforeach</div></fieldset>
    <fieldset class="admin-fieldset admin-field-full"><legend>Sản phẩm liên quan</legend><div class="admin-option-grid">@foreach ($products as $product)<label><input name="product_ids[]" type="checkbox" value="{{ $product->getKey() }}" @checked(in_array($product->getKey(), old('product_ids', $post?->products->pluck('id')->all() ?? [])))><span>{{ $product->name }}</span></label>@endforeach</div></fieldset>
    <label class="admin-field"><span>Trạng thái</span><select name="status" required><option value="draft" @selected(old('status', $post?->status ?? 'draft') === 'draft')>Bản nháp</option><option value="published" @selected(old('status', $post?->status) === 'published')>Xuất bản</option></select></label>
    <label class="admin-field"><span>Thời gian xuất bản</span><input name="published_at" type="datetime-local" value="{{ old('published_at', $post?->published_at?->format('Y-m-d\TH:i')) }}"></label>
    <label class="admin-check"><input name="is_featured" type="checkbox" value="1" @checked(old('is_featured', $post?->is_featured))><span>Bài viết nổi bật</span></label>
    <label class="admin-field"><span>SEO title</span><input name="seo_title" value="{{ old('seo_title', $post?->seo_title) }}" maxlength="70"></label>
    <label class="admin-field admin-field-full"><span>SEO description</span><textarea name="seo_description" rows="3" maxlength="170">{{ old('seo_description', $post?->seo_description) }}</textarea></label>
</div>
