@extends('layouts.admin', ['title' => 'Cấu hình cửa hàng'])
@section('content')
<header class="admin-page-header"><div><p class="admin-eyebrow">Thiết lập hệ thống</p><h1>Cấu hình cửa hàng</h1><p>Thương hiệu, giao diện, SEO, email và kết nối bên ngoài. Secret được mã hóa trong database.</p></div></header>
<form class="admin-settings-form" action="{{ route('admin.settings.update') }}" method="POST" enctype="multipart/form-data">@csrf @method('PATCH')
<details class="admin-settings-group" open><summary><span>01</span><div><strong>Cửa hàng &amp; thương hiệu</strong><small>Liên hệ, logo, favicon và mạng xã hội</small></div></summary><div class="admin-form-grid">
<label class="admin-field"><span>Tên cửa hàng</span><input name="store_name" value="{{ old('store_name', $settings->get('store_name')) }}" required></label><label class="admin-field"><span>Email</span><input name="store_email" type="email" value="{{ old('store_email', $settings->get('store_email')) }}" required></label><label class="admin-field"><span>Điện thoại</span><input name="store_phone" value="{{ old('store_phone', $settings->get('store_phone')) }}"></label><label class="admin-field admin-field-full"><span>Địa chỉ</span><textarea name="store_address">{{ old('store_address', $settings->get('store_address')) }}</textarea></label><label class="admin-field"><span>Facebook URL</span><input name="facebook_url" type="url" value="{{ old('facebook_url', $settings->get('facebook_url')) }}"></label><label class="admin-field"><span>Instagram URL</span><input name="instagram_url" type="url" value="{{ old('instagram_url', $settings->get('instagram_url')) }}"></label><label class="admin-field"><span>Logo</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="admin-field"><span>Favicon</span><input name="favicon" type="file" accept=".png,.ico"></label>
</div></details>
<details class="admin-settings-group"><summary><span>02</span><div><strong>Giao diện &amp; SEO</strong><small>Màu toàn website và metadata mặc định</small></div></summary><div class="admin-form-grid">
@foreach (['appearance_primary'=>'Màu chính','appearance_accent'=>'Màu nhấn','appearance_background'=>'Màu nền'] as $key=>$label)<label class="admin-field admin-color-field"><span>{{ $label }}</span><input name="{{ $key }}" type="color" value="{{ old($key, $settings->get($key)) }}"></label>@endforeach<label class="admin-field admin-field-full"><span>SEO title</span><input name="seo_default_title" value="{{ old('seo_default_title', $settings->get('seo_default_title')) }}" maxlength="70" required></label><label class="admin-field admin-field-full"><span>SEO description</span><textarea name="seo_default_description" maxlength="170" required>{{ old('seo_default_description', $settings->get('seo_default_description')) }}</textarea></label>
</div></details>
<details class="admin-settings-group"><summary><span>03</span><div><strong>Google &amp; Facebook</strong><small>Nhập đủ ID, secret và callback URL để bật</small></div></summary><div class="admin-form-grid">
@foreach (['google'=>'Google','facebook'=>'Facebook'] as $provider=>$label)<label class="admin-field"><span>{{ $label }} Client ID</span><input name="{{ $provider }}_client_id" value="{{ old($provider.'_client_id', $settings->get($provider.'_client_id')) }}"></label><label class="admin-field"><span>{{ $label }} Client Secret</span><input name="{{ $provider }}_client_secret" type="password" placeholder="Để trống để giữ secret"></label><label class="admin-field admin-field-full"><span>{{ $label }} Callback URL</span><input name="{{ $provider }}_redirect_url" type="url" value="{{ old($provider.'_redirect_url', $settings->get($provider.'_redirect_url')) }}" placeholder="{{ route('social.callback', $provider) }}"></label>@endforeach
</div></details>
<details class="admin-settings-group"><summary><span>04</span><div><strong>Email SMTP</strong><small>Gửi xác nhận đơn và thông báo</small></div></summary><div class="admin-form-grid">
@foreach (['smtp_host'=>'SMTP host','smtp_port'=>'Port','smtp_username'=>'Username','mail_from_address'=>'Email gửi','mail_from_name'=>'Tên người gửi'] as $key=>$label)<label class="admin-field"><span>{{ $label }}</span><input name="{{ $key }}" value="{{ old($key, $settings->get($key)) }}"></label>@endforeach<label class="admin-field"><span>Mã hóa</span><select name="smtp_encryption">@foreach (['tls','ssl','none'] as $value)<option value="{{ $value }}" @selected($settings->get('smtp_encryption')===$value)>{{ strtoupper($value) }}</option>@endforeach</select></label><label class="admin-field"><span>SMTP password</span><input name="smtp_password" type="password" placeholder="Để trống để giữ password"></label>
<p class="admin-field admin-field-full admin-action-note">Với Gmail: host <strong>smtp.gmail.com</strong>, port <strong>587</strong>, TLS, username là địa chỉ Gmail gửi và password là <strong>App Password 16 ký tự</strong>. Google OAuth Client Secret không phải SMTP password.</p>
</div></details>
<details class="admin-settings-group"><summary><span>05</span><div><strong>Vận chuyển &amp; thanh toán</strong><small>Nội dung vận hành hiển thị cho khách</small></div></summary><div class="admin-form-grid"><label class="admin-field admin-field-full"><span>Ghi chú vận chuyển</span><textarea name="shipping_note">{{ old('shipping_note', $settings->get('shipping_note')) }}</textarea></label><label class="admin-field admin-field-full"><span>Ghi chú thanh toán</span><textarea name="payment_note">{{ old('payment_note', $settings->get('payment_note')) }}</textarea></label></div></details>
<div class="admin-settings-save"><button class="admin-button admin-button-primary" type="submit">Lưu cấu hình</button></div></form>
@endsection
