<?php

return [
    'defaults' => [
        'store_name' => 'CLARE',
        'store_email' => 'hello@clare.local',
        'store_phone' => '',
        'store_address' => '',
        'facebook_url' => '',
        'instagram_url' => '',
        'logo_path' => '',
        'favicon_path' => '',
        'appearance_primary' => '#79353b',
        'appearance_accent' => '#c49463',
        'appearance_background' => '#f3eee5',
        'seo_default_title' => 'CLARE — Đèn dịu cho những khoảng nghỉ',
        'seo_default_description' => 'Đèn ngủ và đèn trang trí được Clare chọn cho không gian sống ấm, dịu và thân thuộc.',
        'google_client_id' => '',
        'google_client_secret' => '',
        'google_redirect_url' => '',
        'facebook_client_id' => '',
        'facebook_client_secret' => '',
        'facebook_redirect_url' => '',
        'smtp_host' => '',
        'smtp_port' => '587',
        'smtp_encryption' => 'tls',
        'smtp_username' => '',
        'smtp_password' => '',
        'mail_from_address' => 'hello@clare.local',
        'mail_from_name' => 'Clare',
        'shipping_note' => 'Phí giao hàng được tính theo địa chỉ, khối lượng và phương án vận chuyển.',
        'payment_note' => 'Thanh toán được xác nhận theo phương thức bạn chọn.',
    ],
    'secrets' => ['google_client_secret', 'facebook_client_secret', 'smtp_password'],
];
