<?php

return [
    'groups' => [
        'global' => [
            'label' => 'Thông tin chung',
            'description' => 'Thương hiệu, thông báo, tìm kiếm và footer dùng trên toàn bộ cửa hàng.',
            'fields' => [
                'global_site_name' => ['label' => 'Tên thương hiệu', 'type' => 'text', 'default' => 'CLARE', 'max' => 40],
                'global_meta_description' => ['label' => 'Mô tả SEO mặc định', 'type' => 'textarea', 'default' => 'Clare — những mẫu đèn dịu nhẹ cho nhịp sống chậm và căn phòng ấm.', 'max' => 180],
                'global_announcement' => ['label' => 'Dòng thông báo đầu trang', 'type' => 'text', 'default' => 'Đèn được chọn cho những khoảng nghỉ thật sự ở nhà.', 'max' => 180],
                'global_search_placeholder' => ['label' => 'Gợi ý trong ô tìm kiếm', 'type' => 'text', 'default' => 'Tìm đèn bàn, opal, gỗ…', 'max' => 100],
                'global_consultation_label' => ['label' => 'Nhãn nút tư vấn trên header', 'type' => 'text', 'default' => 'Tư vấn chọn đèn', 'max' => 80],
                'global_navigation_eyebrow' => ['label' => 'Mega menu — dòng nhỏ', 'type' => 'text', 'default' => 'Góc được Clare chọn', 'max' => 80],
                'global_navigation_title' => ['label' => 'Mega menu — tiêu đề', 'type' => 'text', 'default' => 'Một điểm sáng dịu cho giờ nghỉ.', 'max' => 120],
                'global_navigation_cta' => ['label' => 'Mega menu — nút', 'type' => 'text', 'default' => 'Khám phá đèn phòng ngủ', 'max' => 80],
                'global_navigation_image' => ['label' => 'Mega menu — ảnh giới thiệu', 'type' => 'image', 'default' => 'images/catalog/banner.png'],
                'global_footer_description' => ['label' => 'Giới thiệu ở footer', 'type' => 'textarea', 'default' => 'Những chiếc đèn được chọn để căn phòng dịu đi, và mỗi buổi tối có thêm một khoảng nghỉ.', 'max' => 320],
                'global_contact_email' => ['label' => 'Email liên hệ', 'type' => 'email', 'default' => 'hello@clare.local', 'max' => 150],
                'global_footer_signature' => ['label' => 'Dòng cuối footer', 'type' => 'text', 'default' => 'Thiết kế và nội dung nguyên bản.', 'max' => 180],
            ],
        ],
        'home_hero' => [
            'label' => 'Trang chủ — Mở đầu',
            'description' => 'Nội dung và ảnh xuất hiện ngay đầu trang chủ.',
            'fields' => [
                'home_meta_description' => ['label' => 'Mô tả SEO trang chủ', 'type' => 'textarea', 'default' => 'Khám phá đèn bàn và đèn tường Clare — ánh sáng ấm, chất liệu tự nhiên và kiểu dáng nhẹ nhàng cho ngôi nhà.', 'max' => 180],
                'home_hero_eyebrow' => ['label' => 'Dòng nhỏ', 'type' => 'text', 'default' => 'Clare / Ánh sáng cho căn nhà', 'max' => 100],
                'home_hero_title_first' => ['label' => 'Tiêu đề — dòng 1', 'type' => 'text', 'default' => 'Đèn dịu.', 'max' => 80],
                'home_hero_title_second' => ['label' => 'Tiêu đề — dòng 2', 'type' => 'text', 'default' => 'Nhịp sống', 'max' => 80],
                'home_hero_title_emphasis' => ['label' => 'Từ nhấn mạnh', 'type' => 'text', 'default' => 'êm.', 'max' => 40],
                'home_hero_intro' => ['label' => 'Đoạn giới thiệu', 'type' => 'textarea', 'default' => 'Khám phá những dáng đèn cho bàn cạnh giường, góc đọc sách và mọi nơi bạn muốn căn phòng trở nên dễ chịu hơn.', 'max' => 420],
                'home_hero_primary_cta' => ['label' => 'Nút chính', 'type' => 'text', 'default' => 'Xem bộ sưu tập', 'max' => 60],
                'home_hero_secondary_cta' => ['label' => 'Nút phụ', 'type' => 'text', 'default' => 'Tìm đèn phù hợp', 'max' => 60],
                'home_hero_image' => ['label' => 'Ảnh hero', 'type' => 'image', 'default' => 'images/catalog/hero-ru-dem.png'],
                'home_hero_image_alt' => ['label' => 'Mô tả ảnh hero', 'type' => 'text', 'default' => 'Đèn Ru Đêm tỏa ánh sáng ấm trên tủ gỗ cạnh giường', 'max' => 180],
                'home_hero_note' => ['label' => 'Ghi chú trên ảnh', 'type' => 'text', 'default' => 'Phòng ngủ / Ánh sáng ấm', 'max' => 100],
            ],
        ],
        'home_editorial' => [
            'label' => 'Trang chủ — Nội dung biên tập',
            'description' => 'Các khối câu chuyện, collection, banner, chất liệu và tư vấn.',
            'fields' => [
                'home_manifesto_eyebrow' => ['label' => 'Manifesto — dòng nhỏ', 'type' => 'text', 'default' => 'Chọn ít hơn, sống cùng lâu hơn', 'max' => 100],
                'home_manifesto_title' => ['label' => 'Manifesto — tiêu đề', 'type' => 'textarea', 'default' => 'Mỗi dáng đèn đều bắt đầu bằng một khoảnh khắc trong nhà.', 'max' => 220],
                'home_manifesto_body' => ['label' => 'Manifesto — nội dung', 'type' => 'textarea', 'default' => 'Clare chọn ánh sáng theo cách bạn sử dụng căn phòng: đủ ấm khi đọc, đủ dịu trước giờ ngủ và vừa vặn cho một góc nhỏ của riêng mình.', 'max' => 480],
                'home_collections_eyebrow' => ['label' => 'Collection — dòng nhỏ', 'type' => 'text', 'default' => 'Khám phá theo không gian', 'max' => 100],
                'home_collections_title' => ['label' => 'Collection — tiêu đề', 'type' => 'text', 'default' => 'Đặt đúng nơi.', 'max' => 100],
                'home_collections_emphasis' => ['label' => 'Collection — dòng nhấn', 'type' => 'text', 'default' => 'Sáng đúng cách.', 'max' => 100],
                'home_collections_description' => ['label' => 'Collection — mô tả', 'type' => 'textarea', 'default' => 'Những bộ sưu tập nhỏ, được biên tập cho các nhịp sống khác nhau trong một căn nhà.', 'max' => 320],
                'home_banner_eyebrow' => ['label' => 'Banner — dòng nhỏ', 'type' => 'text', 'default' => 'Không gian Clare', 'max' => 100],
                'home_banner_title' => ['label' => 'Banner — tiêu đề', 'type' => 'text', 'default' => 'Một dải sáng.', 'max' => 100],
                'home_banner_emphasis' => ['label' => 'Banner — dòng nhấn', 'type' => 'text', 'default' => 'Nhiều khoảng dịu.', 'max' => 100],
                'home_banner_description' => ['label' => 'Banner — mô tả', 'type' => 'textarea', 'default' => 'Mỗi chiếc đèn là một điểm sáng nhỏ; khi đặt cạnh nhau, chúng tạo nên nhịp điệu ấm áp cho cả căn phòng.', 'max' => 360],
                'home_banner_image' => ['label' => 'Ảnh banner', 'type' => 'image', 'default' => 'images/catalog/banner.png'],
                'home_banner_image_alt' => ['label' => 'Mô tả ảnh banner', 'type' => 'text', 'default' => 'Không gian phòng ngủ Clare với nhiều mẫu đèn tỏa ánh sáng ấm', 'max' => 180],
                'home_banner_edition' => ['label' => 'Nhãn trên banner', 'type' => 'text', 'default' => 'The Clare edit / 2026', 'max' => 100],
                'home_banner_cta' => ['label' => 'Nút trên banner', 'type' => 'text', 'default' => 'Xem tất cả đèn', 'max' => 60],
                'home_featured_eyebrow' => ['label' => 'Sản phẩm nổi bật — dòng nhỏ', 'type' => 'text', 'default' => 'Danh mục Clare', 'max' => 100],
                'home_featured_title' => ['label' => 'Sản phẩm nổi bật — tiêu đề', 'type' => 'textarea', 'default' => 'Những mẫu đèn được chọn.', 'max' => 160],
                'home_featured_description' => ['label' => 'Sản phẩm nổi bật — mô tả', 'type' => 'textarea', 'default' => 'Chọn màu, kiểm tra tồn kho và tìm dáng đèn hợp với khoảng nghỉ của bạn.', 'max' => 320],
                'home_story_eyebrow' => ['label' => 'Chất liệu — dòng nhỏ', 'type' => 'text', 'default' => 'Chất liệu tạo nên cảm giác', 'max' => 100],
                'home_story_title' => ['label' => 'Chất liệu — tiêu đề', 'type' => 'text', 'default' => 'Đẹp khi nhìn.', 'max' => 100],
                'home_story_emphasis' => ['label' => 'Chất liệu — dòng nhấn', 'type' => 'text', 'default' => 'Dịu khi sống cùng.', 'max' => 100],
                'home_story_body' => ['label' => 'Chất liệu — nội dung', 'type' => 'textarea', 'default' => 'Gốm mờ, linen dệt thô, thủy tinh opal và kim loại phủ màu trầm được kết hợp để ánh sáng không chỉ hiện ra — mà còn có chiều sâu.', 'max' => 480],
                'home_story_image' => ['label' => 'Ảnh chất liệu', 'type' => 'image', 'default' => 'images/catalog/den-ban-thao-moc.png'],
                'home_story_image_alt' => ['label' => 'Mô tả ảnh chất liệu', 'type' => 'text', 'default' => 'Chi tiết chụp linen và thân gốm của đèn Thảo Mộc', 'max' => 180],
                'home_help_eyebrow' => ['label' => 'Tư vấn — dòng nhỏ', 'type' => 'text', 'default' => 'Cần một chút trợ giúp?', 'max' => 100],
                'home_help_title' => ['label' => 'Tư vấn — tiêu đề', 'type' => 'textarea', 'default' => 'Hãy kể Clare nghe về căn phòng của bạn.', 'max' => 180],
                'home_help_body' => ['label' => 'Tư vấn — nội dung', 'type' => 'textarea', 'default' => 'Chúng tôi sẽ cùng bạn cân nhắc kích thước, nhiệt độ màu và vị trí đặt đèn. Hãy gửi thời gian mong muốn, Clare sẽ xem lại và xác nhận thủ công.', 'max' => 480],
                'home_help_cta' => ['label' => 'Tư vấn — nút', 'type' => 'text', 'default' => 'Gửi yêu cầu tư vấn', 'max' => 80],
            ],
        ],
        'catalog' => [
            'label' => 'Trang tất cả sản phẩm',
            'description' => 'Nội dung chung của trang /products. Tên và mô tả category vẫn sửa ở mục Danh mục.',
            'fields' => [
                'catalog_meta_description' => ['label' => 'Mô tả SEO', 'type' => 'textarea', 'default' => 'Khám phá toàn bộ các mẫu đèn Clare đang có.', 'max' => 180],
                'catalog_hero_eyebrow' => ['label' => 'Hero — dòng nhỏ', 'type' => 'text', 'default' => 'Thư viện ánh sáng / Clare', 'max' => 100],
                'catalog_hero_title' => ['label' => 'Hero — tiêu đề', 'type' => 'text', 'default' => 'Chiếc đèn khiến bạn', 'max' => 100],
                'catalog_hero_emphasis' => ['label' => 'Hero — phần nhấn', 'type' => 'text', 'default' => 'muốn về nhà sớm hơn.', 'max' => 120],
                'catalog_hero_intro' => ['label' => 'Hero — giới thiệu', 'type' => 'textarea', 'default' => 'Từ chiếc đèn nhỏ bên giường đến ánh sáng cho góc đọc sách — mỗi mẫu Clare đều được chọn để căn phòng ấm hơn mà vẫn là chính bạn.', 'max' => 480],
                'catalog_note_price' => ['label' => 'Ghi chú 1', 'type' => 'text', 'default' => 'Giá rõ theo từng màu', 'max' => 80],
                'catalog_note_stock' => ['label' => 'Ghi chú 2', 'type' => 'text', 'default' => 'Tồn kho cập nhật', 'max' => 80],
                'catalog_note_help' => ['label' => 'Ghi chú 3', 'type' => 'text', 'default' => 'Tư vấn khi bạn cần', 'max' => 80],
                'catalog_filter_label' => ['label' => 'Tên bộ lọc', 'type' => 'text', 'default' => 'Chọn theo góc nhà', 'max' => 80],
                'catalog_listing_eyebrow' => ['label' => 'Danh sách — dòng nhỏ', 'type' => 'text', 'default' => 'Dành cho căn phòng của bạn', 'max' => 100],
                'catalog_sort_note' => ['label' => 'Ghi chú sắp xếp', 'type' => 'text', 'default' => 'Clare chọn mẫu nổi bật trước', 'max' => 100],
                'catalog_consultation_title' => ['label' => 'CTA tư vấn — tiêu đề', 'type' => 'textarea', 'default' => 'Chọn đèn cũng giống chọn một người bạn cùng phòng.', 'max' => 220],
                'catalog_consultation_body' => ['label' => 'CTA tư vấn — nội dung', 'type' => 'textarea', 'default' => 'Nó nên vừa vặn, dễ sống cùng và khiến bạn thấy vui mỗi lần bật sáng. Nếu còn phân vân, Clare sẽ cùng bạn chọn.', 'max' => 420],
                'catalog_consultation_cta' => ['label' => 'CTA tư vấn — nút', 'type' => 'text', 'default' => 'Kể Clare nghe', 'max' => 80],
            ],
        ],
        'collection_search' => [
            'label' => 'Collection & Tìm kiếm',
            'description' => 'Nội dung dùng chung cho trang collection và kết quả tìm kiếm.',
            'fields' => [
                'collection_heading_suffix' => ['label' => 'Collection — phần sau tên danh mục', 'type' => 'text', 'default' => 'dành cho góc bạn thương.', 'max' => 120],
                'collection_filter_label' => ['label' => 'Collection — tên bộ lọc', 'type' => 'text', 'default' => 'Khám phá theo góc nhà', 'max' => 100],
                'collection_listing_eyebrow' => ['label' => 'Collection — dòng nhỏ danh sách', 'type' => 'text', 'default' => 'Chọn một chiếc thật vừa', 'max' => 100],
                'collection_guidance_title' => ['label' => 'Collection — tiêu đề tư vấn', 'type' => 'textarea', 'default' => 'Hãy bắt đầu từ nơi bạn muốn chậm lại.', 'max' => 200],
                'collection_guidance_body' => ['label' => 'Collection — nội dung tư vấn', 'type' => 'textarea', 'default' => 'Chọn dáng đèn bạn thấy vui mắt trước. Ở trang chi tiết, Clare sẽ cho bạn xem rõ màu, kích thước, chất liệu và lượng hàng của từng lựa chọn.', 'max' => 480],
                'collection_guidance_cta' => ['label' => 'Collection — nút tư vấn', 'type' => 'text', 'default' => 'Cùng Clare chọn đèn', 'max' => 80],
                'search_hero_eyebrow' => ['label' => 'Tìm kiếm — dòng nhỏ', 'type' => 'text', 'default' => 'Tìm trong Clare', 'max' => 100],
                'search_title_prefix' => ['label' => 'Tìm kiếm — trước từ khóa', 'type' => 'text', 'default' => 'Kết quả cho', 'max' => 80],
                'search_intro' => ['label' => 'Tìm kiếm — giới thiệu', 'type' => 'textarea', 'default' => 'Thử một kiểu đèn, chất liệu hoặc tên góc nhà. Clare sẽ tìm trong những mẫu đang thực sự có bán.', 'max' => 360],
                'search_quick_label' => ['label' => 'Tìm kiếm — nhãn gợi ý', 'type' => 'text', 'default' => 'Hoặc xem nhanh', 'max' => 80],
                'search_results_title' => ['label' => 'Tìm kiếm — tiêu đề có kết quả', 'type' => 'text', 'default' => 'Có thể bạn đang tìm.', 'max' => 120],
                'search_empty_body' => ['label' => 'Tìm kiếm — hướng dẫn khi trống', 'type' => 'textarea', 'default' => 'Thử từ khóa ngắn hơn như “đèn bàn”, “gỗ”, “opal”, hoặc khám phá toàn bộ catalog đang có.', 'max' => 360],
            ],
        ],
        'product_auth' => [
            'label' => 'Chi tiết sản phẩm & Tài khoản',
            'description' => 'Nội dung biên tập dùng chung trên trang chi tiết và màn hình đăng nhập/đăng ký.',
            'fields' => [
                'product_story_eyebrow' => ['label' => 'Sản phẩm — dòng nhỏ câu chuyện', 'type' => 'text', 'default' => 'Câu chuyện thiết kế', 'max' => 100],
                'product_story_title' => ['label' => 'Sản phẩm — tiêu đề câu chuyện', 'type' => 'text', 'default' => 'Ánh sáng ở đúng mức.', 'max' => 140],
                'product_related_eyebrow' => ['label' => 'Sản phẩm liên quan — dòng nhỏ', 'type' => 'text', 'default' => 'Bạn có thể cũng thích', 'max' => 100],
                'product_related_title' => ['label' => 'Sản phẩm liên quan — tiêu đề', 'type' => 'text', 'default' => 'Cùng một bầu không khí.', 'max' => 140],
                'product_consultation_label' => ['label' => 'Nhãn tư vấn sản phẩm', 'type' => 'text', 'default' => 'Nhờ Clare tư vấn', 'max' => 80],
                'auth_image' => ['label' => 'Ảnh đăng nhập/đăng ký', 'type' => 'image', 'default' => 'images/catalog/login.png'],
                'auth_image_label' => ['label' => 'Nhãn truy cập ảnh tài khoản', 'type' => 'text', 'default' => 'Không gian ánh sáng Clare', 'max' => 140],
                'auth_visual_signature' => ['label' => 'Chữ ký trên ảnh tài khoản', 'type' => 'text', 'default' => 'Ánh sáng cho những khoảng nghỉ', 'max' => 140],
                'login_title' => ['label' => 'Đăng nhập — tiêu đề', 'type' => 'text', 'default' => 'Chào mừng bạn trở lại.', 'max' => 120],
                'login_intro' => ['label' => 'Đăng nhập — giới thiệu', 'type' => 'textarea', 'default' => 'Đăng nhập để tiếp tục hành trình chọn đèn, theo dõi đơn hàng và giữ mọi yêu cầu tư vấn trong một nơi.', 'max' => 380],
                'register_title' => ['label' => 'Đăng ký — tiêu đề', 'type' => 'text', 'default' => 'Bắt đầu một khoảng sáng mới.', 'max' => 120],
                'register_intro' => ['label' => 'Đăng ký — giới thiệu', 'type' => 'textarea', 'default' => 'Tạo tài khoản để đặt hàng an toàn, theo dõi từng chặng giao và lưu những yêu cầu tư vấn dành riêng cho không gian của bạn.', 'max' => 380],
            ],
        ],
    ],
];
