@extends('layouts.storefront', ['title' => $post->seo_title ?: $post->title, 'description' => $post->seo_description ?: $post->excerpt, 'bodyClass' => 'blog-show-page'])
@section('content')
    <article class="blog-article">
        <header class="blog-article-header"><div class="shell"><nav class="catalog-breadcrumbs"><a href="{{ route('catalog.home') }}">Trang chủ</a><span>/</span><a href="{{ route('blog.index') }}">Cảm hứng</a><span>/</span><span>{{ $post->title }}</span></nav><p class="eyebrow">{{ $post->category?->name ?? 'Tạp chí Clare' }}</p><h1>{{ $post->title }}</h1><p class="blog-article-excerpt">{{ $post->excerpt }}</p><div class="blog-article-meta"><span>{{ $post->author?->name ?? 'Clare' }}</span><time>{{ $post->published_at?->format('d/m/Y') }}</time><span>{{ max(1, (int) ceil(str_word_count(strip_tags($post->content)) / 220)) }} phút đọc</span></div></div></header>
        @if ($post->featured_image_url)<figure class="shell blog-article-cover"><img src="{{ $post->featured_image_url }}" alt="{{ $post->featured_image_alt ?: $post->title }}"></figure>@endif
        <div class="shell blog-article-layout"><div class="blog-rich-content">{!! $post->content !!}</div><aside><p class="eyebrow">Trong bài này</p>@if ($post->tags->isNotEmpty())<div class="blog-tags">@foreach ($post->tags as $tag)<span>#{{ $tag->name }}</span>@endforeach</div>@endif<a class="button button-secondary" href="{{ route('appointments.create') }}">Nhờ Clare tư vấn</a></aside></div>
    </article>
    @if ($post->products->isNotEmpty())<section class="section"><div class="shell"><div class="related-products-heading"><div><p class="eyebrow">Được nhắc trong bài</p><h2>Những mẫu đèn liên quan</h2></div></div><div class="product-grid product-related-grid">@foreach ($post->products as $product)<x-product-card :product="$product" />@endforeach</div></div></section>@endif
    @if ($relatedPosts->isNotEmpty())<section class="section blog-related-posts"><div class="shell"><p class="eyebrow">Đọc tiếp</p><h2>Câu chuyện cùng chủ đề</h2><div class="blog-related-grid">@foreach ($relatedPosts as $relatedPost)<a href="{{ route('blog.show', $relatedPost) }}"><small>{{ $relatedPost->category?->name }}</small><strong>{{ $relatedPost->title }}</strong><span>Đọc bài →</span></a>@endforeach</div></div></section>@endif
@endsection
